services:
  turtlebot_unizar:
    image: turtlebot_unizar
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: turtlebot_unizar
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 0
      ROS_DOMAIN_ID: 3
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      TURTLEBOT3_MODEL: wafffle
      GAZEBO_MODEL_PATH: /opt/ros/humble/share/turtlebot3_gazebo/models
      
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/kobuki:/dev/kobuki
      # Code
      - ./catkin_ws:/root/catkin_ws
    network_mode: "host"
    command: tail -f /dev/null