services:
  turtlebot_unizar:
    image: turtlebot_unizar
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: turtlebot_unizar
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    privileged: true
    volumes:
      # X11
      - ~/.Xauthority:/root/.Xauthority
      # 
      - /dev/kobuki:/dev/kobuki
      # Code
      - ./catkin_ws:/root/catkin_ws
    network_mode: "host"
    command: tail -f /dev/null

  discovery_server:
    image: osrf/ros:humble-desktop
    network_mode: host
    command: fastdds discovery -i 0 -l husarnet-local -p 11811
    profiles:
      - ground_station